package com.jsp_cns_mon.pub_jsp_cns_all_bre_data_rule_publish;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class pub_cns_combined_flattened_bre implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(generator = "PUB_CNS_COMBINED_FLATTENED_BRE_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "PUB_CNS_COMBINED_FLATTENED_BRE_ID_SEQ", name = "PUB_CNS_COMBINED_FLATTENED_BRE_ID_GENERATOR")
    private java.lang.Long id;

    public pub_cns_combined_flattened_bre() {
    }
    
    public pub_cns_combined_flattened_bre(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}